### ISSUE TITLE
Generating toydata for tiltIndicator

### ISSUE THREAD

**Issue by ysherstyuk** [2DegreesInvesting/tiltDataPipelines#112]
Hi @maurolepore,

As agreed on the email yesterday, we will be working on generating toydata, which will be included to the data pipelines so sample data can be generated from the latest data taken from the storage whenever there is a new release of the package.

I would like to ask you to provide some input on the below.

We need data requirements and data specifications for tiltIndicator and since you already prior developed toydata, can you share some insights on your methodology of selecting sample data (e.g., in selecting companies so that they can be joined with other datasets etc.,)

Please include the above to this ticket so it's easier to trace. And let me know if you need clarification.

Thanks!

**Comment by maurolepore** [comment]
Hi @ysherstyuk,

> We need data requirements and data specifications for tiltIndicator

tiltIndicator is tested with toy datasets in the [tiltToyData package](https://github.com/2DegreesInvesting/tiltToyData):

* You can find the datasets in the directory [inst/extdata/](https://github.com/2DegreesInvesting/tiltToyData/tree/main/inst/extdata) (following [this guidelines](https://r-pkgs.org/data.html#sec-data-extdata)). 
* [Overview of each dataset](https://2degreesinvesting.github.io/tiltToyData/#example).
* [Changelog](https://2degreesinvesting.github.io/tiltToyData/news/index.html)

While small, those datasets are an overkill for most tests, so tiltIndicator defines even smaller and less realistic toy datasets that are just enough to test specific behaviours. You can see an overview of them all [here](https://gist.github.com/maurolepore/44d720a2277991dde1012b60ad658164), and you may want to [search for "example_" in  the tiltIndicator repo](https://github.com/search?q=repo%3A2DegreesInvesting%2FtiltIndicator+example_&type=code).



> Since you already prior developed toydata, can you share some insights on your methodology of selecting sample data (e.g., in selecting companies so that they can be joined with other datasets etc.,)

I did not develop the datasets in tiltToyData. @Tilmon and @kalashsinghal did. You may ask them what their strategy was. I only move them from other places to the tiltToyData.

However, I'm about to create -- for the first time -- some datasets for tiltToyData and the conversation is happening at https://github.com/2DegreesInvesting/tiltToyDataPrivate/pull/1 -- which is private because we're discussing licensed data. I think my strategy will be based on the article "[Creating realistic data](https://docs.ropensci.org/charlatan/articles/creating-realistic-data.html)".






https://docs.ropensci.org/charlatan/

**Comment by ysherstyuk** [comment]
Hi @maurolepore ,

Thanks for the above information! But I thought we agreed that we will be creating toydata for tiltIndicator. Why are you also creating toydata?

Also I don't have access to the private repo.

**Comment by maurolepore** [comment]
@ysherstyuk 

Do you mean why I'm working on https://github.com/2DegreesInvesting/tiltToyDataPrivate/pull/1? 

The thread that resulted in that PR started over 3 weeks ago. You can enjoy the public version of the long conversation [here :-)](https://github.com/2DegreesInvesting/tiltToyData/issues/7). That task was assigned to me but I would happily pass it on to you if you want. You'll need to talk to @AnneSchoenauer though -- as she started it [here](https://github.com/2DegreesInvesting/tiltIndicator/issues/566).

You may also ask @AnneSchoenauer or @Tilmon about your access to licensed data. I don't know who is in the license and who is not -- so better check with them.
