### ISSUE TITLE
Unable to convert table `ecoinvent-v3.9.1` into a pandas dataframe on databricks

### ISSUE THREAD

**Issue by kalashsinghal** [2DegreesInvesting/tiltDataPipelines#63]
Hey @ysherstyuk 

I am trying to convert table `ecoinvent-v3.9.1` into a pandas dataframe, however below code runs for a while and then give this error `python kernel is unresponsive`. Here is the code: 
```
data = spark.read.parquet(f'abfss://raw@storagetiltdevelop.dfs.core.windows.net/ecoinvent-v3.9.1', storate_options = {'sas_token':'personal_sas_token'}).select(['activity_uuid_product_uuid', 'unit', 'ipcc_2021_climate_change_global_warming_potential_gwp100_kg_co2_eq']).toPandas()
```
This issue was not occurring before I asked for some changes in this table you did Yana.

**Comment by ysherstyuk** [comment]
Hi @kalashsinghal,

If the kernel is unresponsive, can you please trying turning off and turning on the cluster. Let me know if the problem persists.

**Comment by kalashsinghal** [comment]
@ysherstyuk 
I have restarted the cluster, although the problem still persists. FYI: this issue is only occurring for this `ecoinvent-v3.9.1` table and not for other tables.

**Comment by SKruthoff** [comment]
Hi, I have done a quick check and it seems like the format of the ecoinvent data is in the way again. As seen below:
![image](https://github.com/2DegreesInvesting/tiltDataPipelines/assets/137387900/f33ed4e9-d217-424a-b787-c5d5b22695ce)
The columns are out of format again, meaning that even though you are selecting the right columns the overflowing data leads to the python kernel being unresponsive due to it being loaded into memory as a whole, which the spark cluster might have a hard time handling. 

The two options that we have here is reformatting the input data behind the ecoinvent-v3.9.1 data or using the cutoff_ao table from the raw layer, as it should be the same data. What do you think?

**Comment by kalashsinghal** [comment]
@SKruthoff 
We can't use the cutoff_ao table because it lacks column `ipcc_2021_climate_change_global_warming_potential_gwp100_kg_co2_eq` which is only present in table `ecoinvent-v3.9.1`. Hence, reformatting the input data inside the ecoinvent-v3.9.1 table is the only option.

**Comment by kalashsinghal** [comment]
@SKruthoff I works now!
