### ISSUE TITLE
Data Quality Checks on output data

### ISSUE THREAD

**Issue by ysherstyuk** [2DegreesInvesting/tiltDataPipelines#69]
Based on a conversation with Anne we have identified the following requirements on a table/output level:

- create aggregation check for the emission ew and worst case and best case
	- should have worst of best case
	- only if it is matched with ecoinvent
- flag if prodcut not matched with ecoinvent
- high/med/low for every benchmark and a value within every benchmark
- check with the scenario mapping table for upper and lower bound
- matching certainty in a list or NA
- not a product required but should be signalling
- block if there is a matched activity and no reference product
- activity and product uuid available 
- sector should be inside the sector mappers
- ep product 
- tilt_sector can only be a single sector 
- compare in other column from a different table 
	specific for sector mappers

These are only descriptions and might be adapted in different levels of the code. For example, where the main activity in the output is required to be in a list, not the output should be checked but the table that is in the data model or raw layer. In this way we avoid duplicating checks.

**Comment by SKruthoff** [comment]
I have adapted the output checks on the existing tables. I have parked the following things because they would require a more significant rewrite of the conditions:
- postcode and addresses are to be looked into in the future
- amount that the input_name needs to be present in the istr_product_results
 I also still have to do a validation of the checks if they display the right values
